#!/bin/sh
mkdir -p /var/mobile/Library/Caches
chmod 777 /var/mobile/Library/Caches
chown mobile /var/mobile/Library/Caches
touch /var/mobile/Library/Caches/libactivator.plist
chmod 666 /var/mobile/Library/Caches/libactivator.plist
chown mobile /var/mobile/Library/Caches/libactivator.plist
exit 0;
